/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#3d3f55",
        "on-background": "#e5e2e1",
        "secondary": "#ffb781",
        "on-secondary-fixed": "#2f1400",
        "primary": "#e8c46a",
        "surface-variant": "#353535",
        "on-primary-fixed": "#251a00",
        "surface": "#131313",
        "on-secondary-container": "#ffcfad",
        "inverse-on-surface": "#313030",
        "surface-container": "#20201f",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#a9aac5",
        "surface-tint": "#e7c268",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#e0e0fc",
        "outline": "#9c8e82",
        "primary-fixed-dim": "#e7c268",
        "secondary-fixed": "#ffdcc4",
        "tertiary-fixed-dim": "#c4c4df",
        "on-tertiary": "#2d2f44",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#6f3800",
        "inverse-primary": "#765a05",
        "secondary-container": "#924c00",
        "on-error": "#690005",
        "tertiary": "#c5c5e1",
        "primary-fixed": "#ffdf96",
        "surface-container-highest": "#353535",
        "outline-variant": "#50453b",
        "surface-bright": "#393939",
        "error": "#ffb4ab",
        "background": "#131313",
        "primary-container": "#cba851",
        "on-secondary": "#4e2600",
        "on-primary-fixed-variant": "#5a4400",
        "secondary-fixed-dim": "#ffb781",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#d4c4b7",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#181a2e",
        "surface-container-low": "#1c1b1b",
        "on-primary": "#3e2e00",
        "on-tertiary-fixed-variant": "#43455b",
        "on-primary-container": "#523d00"
      },
      fontFamily: {
        "headline": ["IBM Plex Sans Arabic", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
